# --- !Ups

create table "humans" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null,
  "ethnicity" varchar not null,
);

# --- !Downs

drop table "humans" if exists;
